apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: authz-engine-base

namespace: authz-system

resources:
  - ../namespace.yaml
  - ../deployment.yaml
  - ../service.yaml
  - ../configmap.yaml
  - ../hpa.yaml
  - ../pdb.yaml
  - ../ingress.yaml

commonLabels:
  app: authz-engine
  managed-by: kustomize

commonAnnotations:
  managed-by: kustomize
